### ISSUE TITLE
Add PHPMyAdmin or Adminer ?

### ISSUE THREAD

**Issue by cedricbommart** [pvtl/docker-dev#11]
Hello guys. Thank you for your work.

Are there any plans to add a PHPMyAdmin or Adminer connection to easily administer the databases ?

**Comment by mcnamee** [comment]
Hi @cedricbommart 
No plans to bundle in a MySQL admin panel out of the box. Our team all use desktop applications such as [TablePlus](https://www.tableplus.io/), [SQLPro](http://www.sequelpro.com/), [MySQL Workbench](https://mysqlworkbench.org/).

Fortunately, with Docker, you can start up a container running tools like PHPMyAdmin that connect to the MySQL server fairly easily:

```bash
docker run --name phpmyadmin -d \
    -e PMA_HOST=mysql \
    --link mysql:db \
    --network docker-dev_lde-network \
    -p 8080:80 \
    phpmyadmin
```

But I might actually add the [PHPMyAdmin container](https://hub.docker.com/_/phpmyadmin?tab=description) to `docker-compose.yml` as an additional service that's commented out so that you can uncomment to add it (if you need it):

```yml
  # PHPMyAdmin ---------------------------------------------------
  phpmyadmin:
    container_name: phpmyadmin
    hostname: phpmyadmin
    restart: ${DOCKER_RESTART}
    image: "phpmyadmin"
    environment:
      - PMA_HOST=mysql
    links:
      - mysql
    ports:
      - "8080:80"
    networks:
      lde-network:
```
